export const QUERY_REQUEST_SEND = 'QUERY REQUEST SEND';
export const QUERY_REQUEST_SUCCESS = 'QUERY REQUEST SUCCESS';
export const QUERY_REQUEST_FAILURE = 'QUERY REQUEST FAILURE';
export const QUERY_REQUEST_PROCESSING = 'QUERY REQUEST PROCESSING';

export const STORED_PROCEDURE_REQUEST_SEND = 'STORED_PROCEDURE_REQUEST_SEND';
export const STORED_PROCEDURE_REQUEST_SUCCESS = 'STORED_PROCEDURE_REQUEST_SUCCESS';
export const STORED_PROCEDURE_REQUEST_FAILURE = 'STORED_PROCEDURE_REQUEST_FAILURE';
export const STORED_PROCEDURE_REQUEST_PROCESSING = 'STORED_PROCEDURE_REQUEST_PROCESSING';

export const RENDER_MAP = 'RENDER_MAP';
export const RENDER_CHART = 'RENDER_CHART';

export const ADD_LAYER = 'ADD_LAYER';

export const STORE_SAMPLE_DATA = 'STORE_SAMPLE_DATA';