export const QUERY_REQUEST_SEND = 'QUERY REQUEST SEND';
export const QUERY_REQUEST_SUCCESS = 'QUERY REQUEST SUCCESS';
export const QUERY_REQUEST_FAILURE = 'QUERY REQUEST FAILURE';
export const QUERY_REQUEST_PROCESSING = 'QUERY REQUEST PROCESSING';

export const ADD_LAYER = 'ADD_LAYER';

export const STORE_SAMPLE_DATA = 'STORE_SAMPLE_DATA';